### ISSUE TITLE
Syntax error running any command

### ISSUE THREAD

**Issue by bcbirkhauser** [unitejs/cli#3]
I am getting an error anytime I try to invoke the cli.  

```
$ unite help
/usr/local/lib/node_modules/unitejs-cli/node_modules/unitejs-framework/dist/loggers/defaultLogger.js:7
    static log(message, ...args) {
                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/unitejs-cli/node_modules/unitejs-cli-core/dist/cliBase.js:11:25)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
```

I installed using ```sudo npm install -g unitejs-cli```

**Comment by obany** [comment]
Could you tell me which version of node you are using by running:
```
node -v
```
I suspect this error is because you are using a version which doesn't support the ... rest syntax of ES6.
The UniteJS tools have only been verified and are only supported on version 8 and above.

**Comment by bcbirkhauser** [comment]
Thanks for the quick response, I upgraded node and that did the trick.  Would be great to have a better error message if possible, or somewhere that lists out the requirements.
